name: Build and Test Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Installer Node.js (si ton projet utilise npm/yarn)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm install

      # 4. Construire le projet (par ex. Next.js, React, Vue, etc.)
      - name: Build project
        run: npm run build

      # 5. Vérifier que ça tourne (tests simples ou echo)
      - name: Run tests
        run: echo "✅ Build terminé avec succès pour Yakoubi-Yamina-Portfolio-Global"
